In [1]:
from datetime import datetime, timedelta

# Start and end dates
start_date_str = "2018-01-01"
end_date_str = "2023-12-01"

# Convert strings to datetime objects
start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
end_date = datetime.strptime(end_date_str, "%Y-%m-%d")

# Initialize current date to the start of the next month
current_date = start_date.replace(day=1) #+ timedelta(days=31)
current_date_2 = (current_date + timedelta(days=31)) #บางที่อาจต้องเปลี่ยนวันตรงนี้ถ้าเลขของเดือนแรกไม่ลงตัว
end_date_2 = end_date.replace(day=1) + timedelta(days=31)
current_date = current_date.replace(day=1)

In [2]:
# Generate dates
dates = []
while current_date <= end_date:
    dates.append(current_date.strftime("%Y-%m-%d"))
    # Move to the next month
    current_date += timedelta(days=31)
    current_date = current_date.replace(day=1)

dates2 = []
while current_date_2 <= end_date_2:
    dates2.append(current_date_2.strftime("%Y-%m-%d"))
    # Move to the next month
    current_date_2 += timedelta(days=31)
    current_date_2 = current_date_2.replace(day=1)

In [3]:
# Concatenate pair by pair
concatenated_dates = [f"'{d1}' '{d2}'" for d1, d2 in zip(dates, dates2)]

# print(dates)
# print(dates2)
print(concatenated_dates)

["'2018-01-01' '2018-02-01'", "'2018-02-01' '2018-03-01'", "'2018-03-01' '2018-04-01'", "'2018-04-01' '2018-05-01'", "'2018-05-01' '2018-06-01'", "'2018-06-01' '2018-07-01'", "'2018-07-01' '2018-08-01'", "'2018-08-01' '2018-09-01'", "'2018-09-01' '2018-10-01'", "'2018-10-01' '2018-11-01'", "'2018-11-01' '2018-12-01'", "'2018-12-01' '2019-01-01'", "'2019-01-01' '2019-02-01'", "'2019-02-01' '2019-03-01'", "'2019-03-01' '2019-04-01'", "'2019-04-01' '2019-05-01'", "'2019-05-01' '2019-06-01'", "'2019-06-01' '2019-07-01'", "'2019-07-01' '2019-08-01'", "'2019-08-01' '2019-09-01'", "'2019-09-01' '2019-10-01'", "'2019-10-01' '2019-11-01'", "'2019-11-01' '2019-12-01'", "'2019-12-01' '2020-01-01'", "'2020-01-01' '2020-02-01'", "'2020-02-01' '2020-03-01'", "'2020-03-01' '2020-04-01'", "'2020-04-01' '2020-05-01'", "'2020-05-01' '2020-06-01'", "'2020-06-01' '2020-07-01'", "'2020-07-01' '2020-08-01'", "'2020-08-01' '2020-09-01'", "'2020-09-01' '2020-10-01'", "'2020-10-01' '2020-11-01'", "'2020-11-01' '2020-12-01'", "'2020-12-01' '2021-01-01'", "'2021-01-01' '2021-02-01'", "'2021-02-01' '2021-03-01'", "'2021-03-01' '2021-04-01'", "'2021-04-01' '2021-05-01'", "'2021-05-01' '2021-06-01'", "'2021-06-01' '2021-07-01'", "'2021-07-01' '2021-08-01'", "'2021-08-01' '2021-09-01'", "'2021-09-01' '2021-10-01'", "'2021-10-01' '2021-11-01'", "'2021-11-01' '2021-12-01'", "'2021-12-01' '2022-01-01'", "'2022-01-01' '2022-02-01'", "'2022-02-01' '2022-03-01'", "'2022-03-01' '2022-04-01'", "'2022-04-01' '2022-05-01'", "'2022-05-01' '2022-06-01'", "'2022-06-01' '2022-07-01'", "'2022-07-01' '2022-08-01'", "'2022-08-01' '2022-09-01'", "'2022-09-01' '2022-10-01'", "'2022-10-01' '2022-11-01'", "'2022-11-01' '2022-12-01'", "'2022-12-01' '2023-01-01'", "'2023-01-01' '2023-02-01'", "'2023-02-01' '2023-03-01'", "'2023-03-01' '2023-04-01'", "'2023-04-01' '2023-05-01'", "'2023-05-01' '2023-06-01'", "'2023-06-01' '2023-07-01'", "'2023-07-01' '2023-08-01'", "'2023-08-01' '2023-09-01'", "'2023-09-01' '2023-10-01'", "'2023-10-01' '2023-11-01'", "'2023-11-01' '2023-12-01'", "'2023-12-01' '2024-01-01'"]

In [9]:
concatenated_dates_list = [(d1, d2) for d1, d2 in zip(dates, dates2)]
concatenated_dates_list.reverse()
for d1, d2 in concatenated_dates_list:
    print(f"'{d1}' '{d2}'")

'2023-12-01' '2024-01-01'
'2023-11-01' '2023-12-01'
'2023-10-01' '2023-11-01'
'2023-09-01' '2023-10-01'
'2023-08-01' '2023-09-01'
'2023-07-01' '2023-08-01'
'2023-06-01' '2023-07-01'
'2023-05-01' '2023-06-01'
'2023-04-01' '2023-05-01'
'2023-03-01' '2023-04-01'
'2023-02-01' '2023-03-01'
'2023-01-01' '2023-02-01'
'2022-12-01' '2023-01-01'
'2022-11-01' '2022-12-01'
'2022-10-01' '2022-11-01'
'2022-09-01' '2022-10-01'
'2022-08-01' '2022-09-01'
'2022-07-01' '2022-08-01'
'2022-06-01' '2022-07-01'
'2022-05-01' '2022-06-01'
'2022-04-01' '2022-05-01'
'2022-03-01' '2022-04-01'
'2022-02-01' '2022-03-01'
'2022-01-01' '2022-02-01'
'2021-12-01' '2022-01-01'
'2021-11-01' '2021-12-01'
'2021-10-01' '2021-11-01'
'2021-09-01' '2021-10-01'
'2021-08-01' '2021-09-01'
'2021-07-01' '2021-08-01'
'2021-06-01' '2021-07-01'
'2021-05-01' '2021-06-01'
'2021-04-01' '2021-05-01'
'2021-03-01' '2021-04-01'
'2021-02-01' '2021-03-01'
'2021-01-01' '2021-02-01'
'2020-12-01' '2021-01-01'
'2020-11-01' '2020-12-01'
'2020-10-01' '2020-11-01'
'2020-09-01' '2020-10-01'
'2020-08-01' '2020-09-01'
'2020-07-01' '2020-08-01'
'2020-06-01' '2020-07-01'
'2020-05-01' '2020-06-01'
'2020-04-01' '2020-05-01'
'2020-03-01' '2020-04-01'
'2020-02-01' '2020-03-01'
'2020-01-01' '2020-02-01'
'2019-12-01' '2020-01-01'
'2019-11-01' '2019-12-01'
'2019-10-01' '2019-11-01'
'2019-09-01' '2019-10-01'
'2019-08-01' '2019-09-01'
'2019-07-01' '2019-08-01'
'2019-06-01' '2019-07-01'
'2019-05-01' '2019-06-01'
'2019-04-01' '2019-05-01'
'2019-03-01' '2019-04-01'
'2019-02-01' '2019-03-01'
'2019-01-01' '2019-02-01'
'2018-12-01' '2019-01-01'
'2018-11-01' '2018-12-01'
'2018-10-01' '2018-11-01'
'2018-09-01' '2018-10-01'
'2018-08-01' '2018-09-01'
'2018-07-01' '2018-08-01'
'2018-06-01' '2018-07-01'
'2018-05-01' '2018-06-01'
'2018-04-01' '2018-05-01'
'2018-03-01' '2018-04-01'
'2018-02-01' '2018-03-01'
'2018-01-01' '2018-02-01'